package edu.newton.ldp.u5.lab5.Prob3;

public class ValidacaoSegundoDigitoException extends Exception{
	public ValidacaoSegundoDigitoException() {
		super("CPF inválido! Falha na verificação do segundo digito após o traço!");
	}
}
